name: test
channels:
  - defaults
  - conda-forge
dependencies:
    # Base
  - numpy
  - python
  - qcelemental
  - msgpack-python

    # Testing
  - pytest
  - pytest-cov
  - psi4
  - simple-dftd3
  - dftd3-python
  - codecov
