name: test
channels:
  - conda-forge
  - defaults
dependencies:
    # Base
  - numpy
  - python
  - qcelemental
  - qcengine
  - msgpack-python
  
    # Testing
  - pytest
  - pytest-cov
  - psi4
  - simple-dftd3
  - dftd3-python
  - codecov

   # Dev
  - sphinx
  - sphinx-automodapi
  - sphinx_material
  - graphviz
  - black
  - isort
