version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-latest"

conda:
  environment: devtools/conda-envs/docs.yaml

sphinx:
  configuration: docs/source/conf.py
