name: CI

on: [push, pull_request]

jobs:
  build:

    # prevent actions from running on both the push to the PR and PR
    # only run actions on PRs originating from a fork
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-tags: true
  
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # not worried about environment in runner just pip install hatch deps
    - name: Install hatch
      shell: bash -l {0}
      run: |
        pip install hatch hatch-vcs hatch-conda

    # Make sure conda is around for hatch-conda
    - name: Create Environment
      uses: conda-incubator/setup-miniconda@v4
      with:
        installer-url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

    # codecov will be generated by hatch for python 3.13 (full test run)
    - name: Test
      shell: bash -l {0}
      run: |
        hatch test -py ${{ matrix.python-version }} optking/tests -n 4

    # Only run if codecov was generated and not running locally for testing (nektos)
    - name: CodeCov
      if: ${{ matrix.python-version }} == "3.13" && ${{ env.ACT }}
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
