name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-tags: true
  
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: install build system
      run:
        pip install hatch hatch-vcs

    - name: build
      run:
        hatch build

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/OptKing
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
